import { Component, OnInit, AfterViewInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';

// PrimeNG Components
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { DropdownModule } from 'primeng/dropdown';
import { TabViewModule } from 'primeng/tabview';
import { CalendarModule } from 'primeng/calendar';
import { InputNumberModule } from 'primeng/inputnumber';
import { TableModule } from 'primeng/table';
import { DialogModule } from 'primeng/dialog';
import { TooltipModule } from 'primeng/tooltip';

declare var google: any;

interface DocumentoAdjunto {
  id: string;
  nombre: string;
  archivo: File | null;
  nombreArchivo: string;
  fechaSubida: Date;
}

@Component({
  selector: 'app-postulacion',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    FormsModule,
    CardModule,
    ButtonModule,
    InputTextModule,
    DropdownModule,
    TabViewModule,
    CalendarModule,
    InputNumberModule,
    TableModule,
    DialogModule,
    TooltipModule
  ],
  templateUrl: './postulacion.component.html',
  styleUrl: './postulacion.component.css'
})
export class PostulacionComponent implements OnInit, AfterViewInit, OnDestroy {
  postulacionForm!: FormGroup;
  programaId: string | null = null;
  
  // Variables para Google Maps
  map: any;
  geocoder: any;
  marker: any;
  autocomplete: any;
  mapCheckInterval: any;

  // Control del acordeón
  activeIndex: number = 0;
  totalSections: number = 18; // Total de secciones del formulario (0-17)
  
  // Documentos adjuntos
  documentosAdjuntos: DocumentoAdjunto[] = [];
  documentoSeleccionado: DocumentoAdjunto | null = null;
  mostrarDialogDocumento: boolean = false;
  archivoSeleccionado: File | null = null;

  // Opciones para dropdowns
  procesoPresupuestarioOptions = [
    { label: '2020', value: '2020' },
    { label: '2021', value: '2021' },
    { label: '2022', value: '2022' },
    { label: '2023', value: '2023' },
    { label: '2024', value: '2024' },
    { label: '2025', value: '2025' }
  ];

  provinciaOptions = [
    { label: 'Provincia Sin Definir', value: '' },
    { label: 'Talca', value: 'Talca' },
    { label: 'Curicó', value: 'Curicó' },
    { label: 'Linares', value: 'Linares' },
    { label: 'Cauquenes', value: 'Cauquenes' }
  ];

  comunaOptions: { label: string; value: string }[] = [
    { label: 'Comuna Sin Definir', value: '' }
  ];
  
  // Comunas por provincia (para referencia)
  private comunasPorProvincia: { [key: string]: { label: string; value: string }[] } = {
    'Talca': [
      { label: 'Seleccione Comuna', value: '' },
      { label: 'Constitución', value: 'Constitución' },
      { label: 'Curepto', value: 'Curepto' },
      { label: 'Empedrado', value: 'Empedrado' },
      { label: 'Maule', value: 'Maule' },
      { label: 'Pelarco', value: 'Pelarco' },
      { label: 'Pencahue', value: 'Pencahue' },
      { label: 'Río Claro', value: 'Río Claro' },
      { label: 'San Clemente', value: 'San Clemente' },
      { label: 'San Rafael', value: 'San Rafael' },
      { label: 'Talca', value: 'Talca' }
    ],
    'Curicó': [
      { label: 'Seleccione Comuna', value: '' },
      { label: 'Curicó', value: 'Curicó' },
      { label: 'Hualañé', value: 'Hualañé' },
      { label: 'Licantén', value: 'Licantén' },
      { label: 'Molina', value: 'Molina' },
      { label: 'Rauco', value: 'Rauco' },
      { label: 'Romeral', value: 'Romeral' },
      { label: 'Sagrada Familia', value: 'Sagrada Familia' },
      { label: 'Teno', value: 'Teno' },
      { label: 'Vichuquén', value: 'Vichuquén' }
    ],
    'Linares': [
      { label: 'Seleccione Comuna', value: '' },
      { label: 'Colbún', value: 'Colbún' },
      { label: 'Linares', value: 'Linares' },
      { label: 'Longaví', value: 'Longaví' },
      { label: 'Parral', value: 'Parral' },
      { label: 'Retiro', value: 'Retiro' },
      { label: 'San Javier', value: 'San Javier' },
      { label: 'Villa Alegre', value: 'Villa Alegre' },
      { label: 'Yerbas Buenas', value: 'Yerbas Buenas' }
    ],
    'Cauquenes': [
      { label: 'Seleccione Comuna', value: '' },
      { label: 'Cauquenes', value: 'Cauquenes' },
      { label: 'Chanco', value: 'Chanco' },
      { label: 'Pelluhue', value: 'Pelluhue' }
    ]
  };

  competenciaOptions = [
    { label: 'SELECCIONAR COMP. DE ANÁLISIS', value: '' },
    { label: 'NACIONAL', value: 'NACIONAL' },
    { label: 'REGIONAL', value: 'REGIONAL' }
  ];

  proyectoRelOptions = [
    { label: 'SELECCIONAR', value: '' },
    { label: 'COMPLEMENTARIO', value: 'COMPLEMENTARIO' },
    { label: 'SIN RELACION', value: 'SIN RELACION' },
    { label: 'SUSTITUTO', value: 'SUSTITUTO' }
  ];

  seiaOptions = [
    { label: 'NO CORRESPONDE', value: '' },
    { label: 'DECLARACIÓN', value: 'DECLARACION' },
    { label: 'ESTUDIO', value: 'ESTUDIO' }
  ];

  desIndigenaOptions = [
    { label: 'Seleccionar una opción', value: '' },
    { label: 'SI', value: 'SI' },
    { label: 'NO', value: 'NO' }
  ];

  magnitudOptions = [
    { label: 'Definir Unidad Medida', value: '' },
    { label: 'HECTAREA', value: 'HECTAREA' },
    { label: 'KILÓMETROS', value: 'KILOMETROS' },
    { label: 'KILOMETROS CUADRADOS', value: 'KILOMETROS CUADRADOS' },
    { label: 'METROS', value: 'METROS' },
    { label: 'METROS CUADRADOS', value: 'METROS CUADRADOS' },
    { label: 'METROS CUBICOS', value: 'METROS CUBICOS' },
    { label: 'METROS CÚBICOS / AÑO', value: 'METROS CUBICOS / AÑO' },
    { label: 'UNIDAD', value: 'UNIDAD' },
    { label: 'LOTE', value: 'LOTE' },
    { label: 'HABITANTE BENEFICIADO', value: 'HABITANTE BENEFICIADO' }
  ];

  remitenteOptions = [
    { label: 'Seleccione', value: '' },
    { label: 'Sra. Alcaldesa', value: '1' },
    { label: 'Sr. Alcalde', value: '2' },
    { label: 'Sra. Directora', value: '3' },
    { label: 'Sr. Director', value: '4' }
  ];

  institucionesFormuladorasOptions = [
    { label: 'Seleccione', value: '' },
    { label: 'ACADEMIA JUDICIAL', value: 'ACADEMIA JUDICIAL' },
    { label: 'AEROPUERTOS MOP REGION DEL MAULE', value: 'AEROPUERTOS MOP REGION DEL MAULE' },
    { label: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE', value: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE' },
    { label: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO', value: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO' },
    { label: 'AGUA POTABLE RURAL', value: 'AGUA POTABLE RURAL' },
    { label: 'AGUA POTABLE RURAL MOP', value: 'AGUA POTABLE RURAL MOP' },
    { label: 'AGUA POTABLE RURAL REGION DEL MAULE', value: 'AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'ARMADA DE CHILE', value: 'ARMADA DE CHILE' },
    { label: 'ARQUITECTURA MOP REGION DEL MAULE', value: 'ARQUITECTURA MOP REGION DEL MAULE' },
    { label: 'CARABINEROS DE CHILE', value: 'CARABINEROS DE CHILE' },
    { label: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)', value: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)' },
    { label: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA', value: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA' },
    { label: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE', value: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE' },
    { label: 'COMISION NACIONAL DE RIEGO', value: 'COMISION NACIONAL DE RIEGO' },
    { label: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL', value: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL' },
    { label: 'CORPORACION DE FOMENTO DE LA PRODUCCION', value: 'CORPORACION DE FOMENTO DE LA PRODUCCION' },
    { label: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE', value: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE' },
    { label: 'CORPORACION NACIONAL FORESTAL', value: 'CORPORACION NACIONAL FORESTAL' },
    { label: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)', value: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)' },
    { label: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE', value: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE' },
    { label: 'CORREOS DE CHILE S.A.', value: 'CORREOS DE CHILE S.A.' },
    { label: 'DEFENSORIA  PENAL PUBLICA', value: 'DEFENSORIA  PENAL PUBLICA' },
    { label: 'DEPARTAMENTO DE INVERSIONES - MDS', value: 'DEPARTAMENTO DE INVERSIONES - MDS' },
    { label: 'DIRECCION AGUAS MOP REGION DEL MAULE', value: 'DIRECCION AGUAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE AEROPUERTOS', value: 'DIRECCION DE AEROPUERTOS' },
    { label: 'DIRECCION DE AEROPUERTOS MOP', value: 'DIRECCION DE AEROPUERTOS MOP' },
    { label: 'DIRECCION DE ARQUITECTURA MOP', value: 'DIRECCION DE ARQUITECTURA MOP' },
    { label: 'DIRECCION DE EDUCACION PUBLICA', value: 'DIRECCION DE EDUCACION PUBLICA' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS', value: 'DIRECCION DE OBRAS HIDRAULICAS' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS', value: 'DIRECCION DE OBRAS PORTUARIAS' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS MOP', value: 'DIRECCION DE OBRAS PORTUARIAS MOP' },
    { label: 'DIRECCION DE PLANEAMIENTO', value: 'DIRECCION DE PLANEAMIENTO' },
    { label: 'DIRECCION DE PLANEAMIENTO MOP', value: 'DIRECCION DE PLANEAMIENTO MOP' },
    { label: 'DIRECCION DE VIALIDAD', value: 'DIRECCION DE VIALIDAD' },
    { label: 'DIRECCION DE VIALIDAD MOP', value: 'DIRECCION DE VIALIDAD MOP' },
    { label: 'DIRECCION DEL TRABAJO', value: 'DIRECCION DEL TRABAJO' },
    { label: 'DIRECCION GENERAL DE AGUAS', value: 'DIRECCION GENERAL DE AGUAS' },
    { label: 'DIRECCION GENERAL DE AGUAS MOP', value: 'DIRECCION GENERAL DE AGUAS MOP' },
    { label: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS', value: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS' },
    { label: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE', value: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE' },
    { label: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA', value: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA' },
    { label: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE', value: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE' },
    { label: 'EMALCO', value: 'EMALCO' },
    { label: 'EMPRESA DE FERROCARRILES DEL ESTADO', value: 'EMPRESA DE FERROCARRILES DEL ESTADO' },
    { label: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE', value: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE' },
    { label: 'GENDARMERIA DE CHILE', value: 'GENDARMERIA DE CHILE' },
    { label: 'GENDARMERIA REGION DEL MAULE', value: 'GENDARMERIA REGION DEL MAULE' },
    { label: 'GOBIERNO REGIONAL - REGION DEL MAULE', value: 'GOBIERNO REGIONAL - REGION DEL MAULE' },
    { label: 'INDESPA', value: 'INDESPA' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO', value: 'INSTITUTO DESARROLLO AGROPECUARIO' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE', value: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE' },
    { label: 'INSTITUTO FORESTAL REGION DEL MAULE', value: 'INSTITUTO FORESTAL REGION DEL MAULE' },
    { label: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE', value: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES', value: 'INSTITUTO NACIONAL DE DEPORTES' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE' },
    { label: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA', value: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA' },
    { label: 'INVESTIGACIONES REGION DEL MAULE', value: 'INVESTIGACIONES REGION DEL MAULE' },
    { label: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS', value: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS' },
    { label: 'JUNTA NACIONAL DE JARDINES INFANTILES', value: 'JUNTA NACIONAL DE JARDINES INFANTILES' },
    { label: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE', value: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE' },
    { label: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA', value: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA' },
    { label: 'MINISTERIO DE HACIENDA', value: 'MINISTERIO DE HACIENDA' },
    { label: 'MINISTERIO DE MEDIO AMBIENTE', value: 'MINISTERIO DE MEDIO AMBIENTE' },
    { label: 'MINISTERIO DE MINERIA', value: 'MINISTERIO DE MINERIA' },
    { label: 'MINISTERIO DE RELACIONES EXTERIORES', value: 'MINISTERIO DE RELACIONES EXTERIORES' },
    { label: 'MINISTERIO DE SALUD', value: 'MINISTERIO DE SALUD' },
    { label: 'MINISTERIO DE VIVIENDA Y URBANISMO', value: 'MINISTERIO DE VIVIENDA Y URBANISMO' },
    { label: 'MINISTERIO PUBLICO', value: 'MINISTERIO PUBLICO' },
    { label: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO', value: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO' },
    { label: 'MUNICIPALIDAD DE CAUQUENES', value: 'MUNICIPALIDAD DE CAUQUENES' },
    { label: 'MUNICIPALIDAD DE CHANCO', value: 'MUNICIPALIDAD DE CHANCO' },
    { label: 'MUNICIPALIDAD DE COLBUN', value: 'MUNICIPALIDAD DE COLBUN' },
    { label: 'MUNICIPALIDAD DE CONSTITUCION', value: 'MUNICIPALIDAD DE CONSTITUCION' },
    { label: 'MUNICIPALIDAD DE CUREPTO', value: 'MUNICIPALIDAD DE CUREPTO' },
    { label: 'MUNICIPALIDAD DE CURICO', value: 'MUNICIPALIDAD DE CURICO' },
    { label: 'MUNICIPALIDAD DE EMPEDRADO', value: 'MUNICIPALIDAD DE EMPEDRADO' },
    { label: 'MUNICIPALIDAD DE HUALAÑE', value: 'MUNICIPALIDAD DE HUALAÑE' },
    { label: 'MUNICIPALIDAD DE LICANTEN', value: 'MUNICIPALIDAD DE LICANTEN' },
    { label: 'MUNICIPALIDAD DE LINARES', value: 'MUNICIPALIDAD DE LINARES' },
    { label: 'MUNICIPALIDAD DE LONGAVI', value: 'MUNICIPALIDAD DE LONGAVI' },
    { label: 'MUNICIPALIDAD DE MAULE', value: 'MUNICIPALIDAD DE MAULE' },
    { label: 'MUNICIPALIDAD DE MOLINA', value: 'MUNICIPALIDAD DE MOLINA' },
    { label: 'MUNICIPALIDAD DE PARRAL', value: 'MUNICIPALIDAD DE PARRAL' },
    { label: 'MUNICIPALIDAD DE PELARCO', value: 'MUNICIPALIDAD DE PELARCO' },
    { label: 'MUNICIPALIDAD DE PELLUHUE', value: 'MUNICIPALIDAD DE PELLUHUE' },
    { label: 'MUNICIPALIDAD DE PENCAHUE', value: 'MUNICIPALIDAD DE PENCAHUE' },
    { label: 'MUNICIPALIDAD DE RAUCO', value: 'MUNICIPALIDAD DE RAUCO' },
    { label: 'MUNICIPALIDAD DE RETIRO', value: 'MUNICIPALIDAD DE RETIRO' },
    { label: 'MUNICIPALIDAD DE RIO CLARO', value: 'MUNICIPALIDAD DE RIO CLARO' },
    { label: 'MUNICIPALIDAD DE ROMERAL', value: 'MUNICIPALIDAD DE ROMERAL' },
    { label: 'MUNICIPALIDAD DE SAGRADA FAMILIA', value: 'MUNICIPALIDAD DE SAGRADA FAMILIA' },
    { label: 'MUNICIPALIDAD DE SAN CLEMENTE', value: 'MUNICIPALIDAD DE SAN CLEMENTE' },
    { label: 'MUNICIPALIDAD DE SAN JAVIER', value: 'MUNICIPALIDAD DE SAN JAVIER' },
    { label: 'MUNICIPALIDAD DE SAN RAFAEL', value: 'MUNICIPALIDAD DE SAN RAFAEL' },
    { label: 'MUNICIPALIDAD DE TALCA', value: 'MUNICIPALIDAD DE TALCA' },
    { label: 'MUNICIPALIDAD DE TENO', value: 'MUNICIPALIDAD DE TENO' },
    { label: 'MUNICIPALIDAD DE VICHUQUEN', value: 'MUNICIPALIDAD DE VICHUQUEN' },
    { label: 'MUNICIPALIDAD DE VILLA ALEGRE', value: 'MUNICIPALIDAD DE VILLA ALEGRE' },
    { label: 'MUNICIPALIDAD DE YERBAS BUENAS', value: 'MUNICIPALIDAD DE YERBAS BUENAS' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO', value: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL MAULE', value: 'OBRAS PORTUARIAS MOP REGION DEL MAULE' },
    { label: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE', value: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE' },
    { label: 'POLICIA DE INVESTIGACIONES DE CHILE', value: 'POLICIA DE INVESTIGACIONES DE CHILE' },
    { label: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)', value: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)' },
    { label: 'SECTRA', value: 'SECTRA' },
    { label: 'SENAPRED REGION DEL MAULE', value: 'SENAPRED REGION DEL MAULE' },
    { label: 'SEREMI AGRICULTURA REGION DEL MAULE', value: 'SEREMI AGRICULTURA REGION DEL MAULE' },
    { label: 'SEREMI BIENES NACIONALES REGION DEL MAULE', value: 'SEREMI BIENES NACIONALES REGION DEL MAULE' },
    { label: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE', value: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE' },
    { label: 'SEREMI DE ENERGIA REGION DEL MAULE', value: 'SEREMI DE ENERGIA REGION DEL MAULE' },
    { label: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE', value: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE' },
    { label: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE', value: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE' },
    { label: 'SEREMI DEL DEPORTE REGION DEL MAULE', value: 'SEREMI DEL DEPORTE REGION DEL MAULE' },
    { label: 'SEREMI ECONOMIA REGION DEL MAULE', value: 'SEREMI ECONOMIA REGION DEL MAULE' },
    { label: 'SEREMI EDUCACION REGION DEL MAULE', value: 'SEREMI EDUCACION REGION DEL MAULE' },
    { label: 'SEREMI SALUD REGION DEL MAULE', value: 'SEREMI SALUD REGION DEL MAULE' },
    { label: 'SEREMI TRABAJO REGION DEL MAULE', value: 'SEREMI TRABAJO REGION DEL MAULE' },
    { label: 'SEREMI TRANSPORTES REGION DEL MAULE', value: 'SEREMI TRANSPORTES REGION DEL MAULE' },
    { label: 'SEREMI VIVIENDA REGION DEL MAULE', value: 'SEREMI VIVIENDA REGION DEL MAULE' },
    { label: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE', value: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE' },
    { label: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE', value: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE', value: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE' },
    { label: 'SERVICIO DE GOBIERNO INTERIOR', value: 'SERVICIO DE GOBIERNO INTERIOR' },
    { label: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION', value: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION' },
    { label: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA' },
    { label: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA' },
    { label: 'SERVICIO MEDICO LEGAL', value: 'SERVICIO MEDICO LEGAL' },
    { label: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE', value: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE MENORES', value: 'SERVICIO NACIONAL DE MENORES' },
    { label: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE', value: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DEL ADULTO MAYOR', value: 'SERVICIO NACIONAL DEL ADULTO MAYOR' },
    { label: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL', value: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL' },
    { label: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE', value: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE' },
    { label: 'SERVICIO SALUD MAULE', value: 'SERVICIO SALUD MAULE' },
    { label: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE', value: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE' },
    { label: 'SUBSECRETARIA DE EDUCACION', value: 'SUBSECRETARIA DE EDUCACION' },
    { label: 'SUBSECRETARIA DE JUSTICIA', value: 'SUBSECRETARIA DE JUSTICIA' },
    { label: 'SUBSECRETARIA DE PESCA', value: 'SUBSECRETARIA DE PESCA' },
    { label: 'SUBSECRETARIA DE TELECOMUNICACIONES', value: 'SUBSECRETARIA DE TELECOMUNICACIONES' },
    { label: 'SUBSECRETARIA DE TRANSPORTES', value: 'SUBSECRETARIA DE TRANSPORTES' },
    { label: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO', value: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO' },
    { label: 'SUBSECRETARIA VIVIENDA Y URBANISMO', value: 'SUBSECRETARIA VIVIENDA Y URBANISMO' },
    { label: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO', value: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO' },
    { label: 'SUPERINTENDENCIA DE EDUCACION', value: 'SUPERINTENDENCIA DE EDUCACION' },
    { label: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO', value: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO' },
    { label: 'VIALIDAD MOP REGION DEL MAULE', value: 'VIALIDAD MOP REGION DEL MAULE' }
  ];

  institucionesFinancierasOptions = [
    { label: 'Seleccione', value: '' },
    { label: 'ACADEMIA JUDICIAL', value: 'ACADEMIA JUDICIAL' },
    { label: 'AEROPUERTOS MOP REGION DEL MAULE', value: 'AEROPUERTOS MOP REGION DEL MAULE' },
    { label: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE', value: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE' },
    { label: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO', value: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO' },
    { label: 'AGUA POTABLE RURAL', value: 'AGUA POTABLE RURAL' },
    { label: 'AGUA POTABLE RURAL MOP', value: 'AGUA POTABLE RURAL MOP' },
    { label: 'AGUA POTABLE RURAL REGION DEL MAULE', value: 'AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'ARMADA DE CHILE', value: 'ARMADA DE CHILE' },
    { label: 'ARQUITECTURA MOP REGION DEL MAULE', value: 'ARQUITECTURA MOP REGION DEL MAULE' },
    { label: 'CARABINEROS DE CHILE', value: 'CARABINEROS DE CHILE' },
    { label: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)', value: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)' },
    { label: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA', value: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA' },
    { label: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE', value: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE' },
    { label: 'COMISION NACIONAL DE RIEGO', value: 'COMISION NACIONAL DE RIEGO' },
    { label: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL', value: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL' },
    { label: 'CORPORACION DE FOMENTO DE LA PRODUCCION', value: 'CORPORACION DE FOMENTO DE LA PRODUCCION' },
    { label: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE', value: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE' },
    { label: 'CORPORACION NACIONAL FORESTAL', value: 'CORPORACION NACIONAL FORESTAL' },
    { label: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)', value: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)' },
    { label: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE', value: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE' },
    { label: 'CORREOS DE CHILE S.A.', value: 'CORREOS DE CHILE S.A.' },
    { label: 'DEFENSORIA  PENAL PUBLICA', value: 'DEFENSORIA  PENAL PUBLICA' },
    { label: 'DEPARTAMENTO DE INVERSIONES - MDS', value: 'DEPARTAMENTO DE INVERSIONES - MDS' },
    { label: 'DIRECCION AGUAS MOP REGION DEL MAULE', value: 'DIRECCION AGUAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE AEROPUERTOS', value: 'DIRECCION DE AEROPUERTOS' },
    { label: 'DIRECCION DE AEROPUERTOS MOP', value: 'DIRECCION DE AEROPUERTOS MOP' },
    { label: 'DIRECCION DE ARQUITECTURA MOP', value: 'DIRECCION DE ARQUITECTURA MOP' },
    { label: 'DIRECCION DE EDUCACION PUBLICA', value: 'DIRECCION DE EDUCACION PUBLICA' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS', value: 'DIRECCION DE OBRAS HIDRAULICAS' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS', value: 'DIRECCION DE OBRAS PORTUARIAS' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS MOP', value: 'DIRECCION DE OBRAS PORTUARIAS MOP' },
    { label: 'DIRECCION DE PLANEAMIENTO', value: 'DIRECCION DE PLANEAMIENTO' },
    { label: 'DIRECCION DE PLANEAMIENTO MOP', value: 'DIRECCION DE PLANEAMIENTO MOP' },
    { label: 'DIRECCION DE VIALIDAD', value: 'DIRECCION DE VIALIDAD' },
    { label: 'DIRECCION DE VIALIDAD MOP', value: 'DIRECCION DE VIALIDAD MOP' },
    { label: 'DIRECCION DEL TRABAJO', value: 'DIRECCION DEL TRABAJO' },
    { label: 'DIRECCION GENERAL DE AGUAS', value: 'DIRECCION GENERAL DE AGUAS' },
    { label: 'DIRECCION GENERAL DE AGUAS MOP', value: 'DIRECCION GENERAL DE AGUAS MOP' },
    { label: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS', value: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS' },
    { label: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE', value: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE' },
    { label: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA', value: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA' },
    { label: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE', value: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE' },
    { label: 'EMALCO', value: 'EMALCO' },
    { label: 'EMPRESA DE FERROCARRILES DEL ESTADO', value: 'EMPRESA DE FERROCARRILES DEL ESTADO' },
    { label: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE', value: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE' },
    { label: 'GENDARMERIA DE CHILE', value: 'GENDARMERIA DE CHILE' },
    { label: 'GENDARMERIA REGION DEL MAULE', value: 'GENDARMERIA REGION DEL MAULE' },
    { label: 'GOBIERNO REGIONAL - REGION DEL MAULE', value: 'GOBIERNO REGIONAL - REGION DEL MAULE' },
    { label: 'INDESPA', value: 'INDESPA' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO', value: 'INSTITUTO DESARROLLO AGROPECUARIO' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE', value: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE' },
    { label: 'INSTITUTO FORESTAL REGION DEL MAULE', value: 'INSTITUTO FORESTAL REGION DEL MAULE' },
    { label: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE', value: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES', value: 'INSTITUTO NACIONAL DE DEPORTES' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE' },
    { label: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA', value: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA' },
    { label: 'INVESTIGACIONES REGION DEL MAULE', value: 'INVESTIGACIONES REGION DEL MAULE' },
    { label: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS', value: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS' },
    { label: 'JUNTA NACIONAL DE JARDINES INFANTILES', value: 'JUNTA NACIONAL DE JARDINES INFANTILES' },
    { label: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE', value: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE' },
    { label: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA', value: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA' },
    { label: 'MINISTERIO DE HACIENDA', value: 'MINISTERIO DE HACIENDA' },
    { label: 'MINISTERIO DE MEDIO AMBIENTE', value: 'MINISTERIO DE MEDIO AMBIENTE' },
    { label: 'MINISTERIO DE MINERIA', value: 'MINISTERIO DE MINERIA' },
    { label: 'MINISTERIO DE RELACIONES EXTERIORES', value: 'MINISTERIO DE RELACIONES EXTERIORES' },
    { label: 'MINISTERIO DE SALUD', value: 'MINISTERIO DE SALUD' },
    { label: 'MINISTERIO DE VIVIENDA Y URBANISMO', value: 'MINISTERIO DE VIVIENDA Y URBANISMO' },
    { label: 'MINISTERIO PUBLICO', value: 'MINISTERIO PUBLICO' },
    { label: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO', value: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO' },
    { label: 'MUNICIPALIDAD DE CAUQUENES', value: 'MUNICIPALIDAD DE CAUQUENES' },
    { label: 'MUNICIPALIDAD DE CHANCO', value: 'MUNICIPALIDAD DE CHANCO' },
    { label: 'MUNICIPALIDAD DE COLBUN', value: 'MUNICIPALIDAD DE COLBUN' },
    { label: 'MUNICIPALIDAD DE CONSTITUCION', value: 'MUNICIPALIDAD DE CONSTITUCION' },
    { label: 'MUNICIPALIDAD DE CUREPTO', value: 'MUNICIPALIDAD DE CUREPTO' },
    { label: 'MUNICIPALIDAD DE CURICO', value: 'MUNICIPALIDAD DE CURICO' },
    { label: 'MUNICIPALIDAD DE EMPEDRADO', value: 'MUNICIPALIDAD DE EMPEDRADO' },
    { label: 'MUNICIPALIDAD DE HUALAÑE', value: 'MUNICIPALIDAD DE HUALAÑE' },
    { label: 'MUNICIPALIDAD DE LICANTEN', value: 'MUNICIPALIDAD DE LICANTEN' },
    { label: 'MUNICIPALIDAD DE LINARES', value: 'MUNICIPALIDAD DE LINARES' },
    { label: 'MUNICIPALIDAD DE LONGAVI', value: 'MUNICIPALIDAD DE LONGAVI' },
    { label: 'MUNICIPALIDAD DE MAULE', value: 'MUNICIPALIDAD DE MAULE' },
    { label: 'MUNICIPALIDAD DE MOLINA', value: 'MUNICIPALIDAD DE MOLINA' },
    { label: 'MUNICIPALIDAD DE PARRAL', value: 'MUNICIPALIDAD DE PARRAL' },
    { label: 'MUNICIPALIDAD DE PELARCO', value: 'MUNICIPALIDAD DE PELARCO' },
    { label: 'MUNICIPALIDAD DE PELLUHUE', value: 'MUNICIPALIDAD DE PELLUHUE' },
    { label: 'MUNICIPALIDAD DE PENCAHUE', value: 'MUNICIPALIDAD DE PENCAHUE' },
    { label: 'MUNICIPALIDAD DE RAUCO', value: 'MUNICIPALIDAD DE RAUCO' },
    { label: 'MUNICIPALIDAD DE RETIRO', value: 'MUNICIPALIDAD DE RETIRO' },
    { label: 'MUNICIPALIDAD DE RIO CLARO', value: 'MUNICIPALIDAD DE RIO CLARO' },
    { label: 'MUNICIPALIDAD DE ROMERAL', value: 'MUNICIPALIDAD DE ROMERAL' },
    { label: 'MUNICIPALIDAD DE SAGRADA FAMILIA', value: 'MUNICIPALIDAD DE SAGRADA FAMILIA' },
    { label: 'MUNICIPALIDAD DE SAN CLEMENTE', value: 'MUNICIPALIDAD DE SAN CLEMENTE' },
    { label: 'MUNICIPALIDAD DE SAN JAVIER', value: 'MUNICIPALIDAD DE SAN JAVIER' },
    { label: 'MUNICIPALIDAD DE SAN RAFAEL', value: 'MUNICIPALIDAD DE SAN RAFAEL' },
    { label: 'MUNICIPALIDAD DE TALCA', value: 'MUNICIPALIDAD DE TALCA' },
    { label: 'MUNICIPALIDAD DE TENO', value: 'MUNICIPALIDAD DE TENO' },
    { label: 'MUNICIPALIDAD DE VICHUQUEN', value: 'MUNICIPALIDAD DE VICHUQUEN' },
    { label: 'MUNICIPALIDAD DE VILLA ALEGRE', value: 'MUNICIPALIDAD DE VILLA ALEGRE' },
    { label: 'MUNICIPALIDAD DE YERBAS BUENAS', value: 'MUNICIPALIDAD DE YERBAS BUENAS' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO', value: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL MAULE', value: 'OBRAS PORTUARIAS MOP REGION DEL MAULE' },
    { label: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE', value: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE' },
    { label: 'POLICIA DE INVESTIGACIONES DE CHILE', value: 'POLICIA DE INVESTIGACIONES DE CHILE' },
    { label: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)', value: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)' },
    { label: 'SECTRA', value: 'SECTRA' },
    { label: 'SENAPRED REGION DEL MAULE', value: 'SENAPRED REGION DEL MAULE' },
    { label: 'SEREMI AGRICULTURA REGION DEL MAULE', value: 'SEREMI AGRICULTURA REGION DEL MAULE' },
    { label: 'SEREMI BIENES NACIONALES REGION DEL MAULE', value: 'SEREMI BIENES NACIONALES REGION DEL MAULE' },
    { label: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE', value: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE' },
    { label: 'SEREMI DE ENERGIA REGION DEL MAULE', value: 'SEREMI DE ENERGIA REGION DEL MAULE' },
    { label: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE', value: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE' },
    { label: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE', value: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE' },
    { label: 'SEREMI DEL DEPORTE REGION DEL MAULE', value: 'SEREMI DEL DEPORTE REGION DEL MAULE' },
    { label: 'SEREMI ECONOMIA REGION DEL MAULE', value: 'SEREMI ECONOMIA REGION DEL MAULE' },
    { label: 'SEREMI EDUCACION REGION DEL MAULE', value: 'SEREMI EDUCACION REGION DEL MAULE' },
    { label: 'SEREMI SALUD REGION DEL MAULE', value: 'SEREMI SALUD REGION DEL MAULE' },
    { label: 'SEREMI TRABAJO REGION DEL MAULE', value: 'SEREMI TRABAJO REGION DEL MAULE' },
    { label: 'SEREMI TRANSPORTES REGION DEL MAULE', value: 'SEREMI TRANSPORTES REGION DEL MAULE' },
    { label: 'SEREMI VIVIENDA REGION DEL MAULE', value: 'SEREMI VIVIENDA REGION DEL MAULE' },
    { label: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE', value: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE' },
    { label: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE', value: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE', value: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE' },
    { label: 'SERVICIO DE GOBIERNO INTERIOR', value: 'SERVICIO DE GOBIERNO INTERIOR' },
    { label: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION', value: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION' },
    { label: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA' },
    { label: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA' },
    { label: 'SERVICIO MEDICO LEGAL', value: 'SERVICIO MEDICO LEGAL' },
    { label: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE', value: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE MENORES', value: 'SERVICIO NACIONAL DE MENORES' },
    { label: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE', value: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DEL ADULTO MAYOR', value: 'SERVICIO NACIONAL DEL ADULTO MAYOR' },
    { label: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL', value: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL' },
    { label: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE', value: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE' },
    { label: 'SERVICIO SALUD MAULE', value: 'SERVICIO SALUD MAULE' },
    { label: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE', value: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE' },
    { label: 'SUBSECRETARIA DE EDUCACION', value: 'SUBSECRETARIA DE EDUCACION' },
    { label: 'SUBSECRETARIA DE JUSTICIA', value: 'SUBSECRETARIA DE JUSTICIA' },
    { label: 'SUBSECRETARIA DE PESCA', value: 'SUBSECRETARIA DE PESCA' },
    { label: 'SUBSECRETARIA DE TELECOMUNICACIONES', value: 'SUBSECRETARIA DE TELECOMUNICACIONES' },
    { label: 'SUBSECRETARIA DE TRANSPORTES', value: 'SUBSECRETARIA DE TRANSPORTES' },
    { label: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO', value: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO' },
    { label: 'SUBSECRETARIA VIVIENDA Y URBANISMO', value: 'SUBSECRETARIA VIVIENDA Y URBANISMO' },
    { label: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO', value: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO' },
    { label: 'SUPERINTENDENCIA DE EDUCACION', value: 'SUPERINTENDENCIA DE EDUCACION' },
    { label: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO', value: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO' },
    { label: 'VIALIDAD MOP REGION DEL MAULE', value: 'VIALIDAD MOP REGION DEL MAULE' }
  ];

  institucionesTecnicasOptions = [
    { label: 'Seleccione', value: '' },
    { label: 'ACADEMIA JUDICIAL', value: 'ACADEMIA JUDICIAL' },
    { label: 'AEROPUERTOS MOP REGION DEL MAULE', value: 'AEROPUERTOS MOP REGION DEL MAULE' },
    { label: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE', value: 'AGENCIA DE COOPERACION INTERNACIONAL DE CHILE' },
    { label: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO', value: 'AGENCIA DE SUSTENTABILIDAD Y CAMBIO CLIMATICO' },
    { label: 'AGUA POTABLE RURAL', value: 'AGUA POTABLE RURAL' },
    { label: 'AGUA POTABLE RURAL MOP', value: 'AGUA POTABLE RURAL MOP' },
    { label: 'AGUA POTABLE RURAL REGION DEL MAULE', value: 'AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'ARMADA DE CHILE', value: 'ARMADA DE CHILE' },
    { label: 'ARQUITECTURA MOP REGION DEL MAULE', value: 'ARQUITECTURA MOP REGION DEL MAULE' },
    { label: 'CARABINEROS DE CHILE', value: 'CARABINEROS DE CHILE' },
    { label: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)', value: 'CENTRO DE INFORMACION RECURSOS NATURALES (CIREN)' },
    { label: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA', value: 'COMERCIALIZADORA DE TRIGO S.A.- COTRISA' },
    { label: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE', value: 'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TE' },
    { label: 'COMISION NACIONAL DE RIEGO', value: 'COMISION NACIONAL DE RIEGO' },
    { label: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL', value: 'CORPORACION ADMINISTRATIVA DEL PODER JUDICIAL' },
    { label: 'CORPORACION DE FOMENTO DE LA PRODUCCION', value: 'CORPORACION DE FOMENTO DE LA PRODUCCION' },
    { label: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE', value: 'CORPORACION FOMENTO DE LA PRODUCCION REGION DEL MAULE' },
    { label: 'CORPORACION NACIONAL FORESTAL', value: 'CORPORACION NACIONAL FORESTAL' },
    { label: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)', value: 'CORPORACION NACIONAL FORESTAL - AREAS SILVESTRES PROTEGIDAS (01,02,03)' },
    { label: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE', value: 'CORPORACION NACIONAL FORESTAL REGION DEL MAULE' },
    { label: 'CORREOS DE CHILE S.A.', value: 'CORREOS DE CHILE S.A.' },
    { label: 'DEFENSORIA  PENAL PUBLICA', value: 'DEFENSORIA  PENAL PUBLICA' },
    { label: 'DEPARTAMENTO DE INVERSIONES - MDS', value: 'DEPARTAMENTO DE INVERSIONES - MDS' },
    { label: 'DIRECCION AGUAS MOP REGION DEL MAULE', value: 'DIRECCION AGUAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE AEROPUERTOS', value: 'DIRECCION DE AEROPUERTOS' },
    { label: 'DIRECCION DE AEROPUERTOS MOP', value: 'DIRECCION DE AEROPUERTOS MOP' },
    { label: 'DIRECCION DE ARQUITECTURA MOP', value: 'DIRECCION DE ARQUITECTURA MOP' },
    { label: 'DIRECCION DE EDUCACION PUBLICA', value: 'DIRECCION DE EDUCACION PUBLICA' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS', value: 'DIRECCION DE OBRAS HIDRAULICAS' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP' },
    { label: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE', value: 'DIRECCION DE OBRAS HIDRAULICAS MOP REGION DEL MAULE' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS', value: 'DIRECCION DE OBRAS PORTUARIAS' },
    { label: 'DIRECCION DE OBRAS PORTUARIAS MOP', value: 'DIRECCION DE OBRAS PORTUARIAS MOP' },
    { label: 'DIRECCION DE PLANEAMIENTO', value: 'DIRECCION DE PLANEAMIENTO' },
    { label: 'DIRECCION DE PLANEAMIENTO MOP', value: 'DIRECCION DE PLANEAMIENTO MOP' },
    { label: 'DIRECCION DE VIALIDAD', value: 'DIRECCION DE VIALIDAD' },
    { label: 'DIRECCION DE VIALIDAD MOP', value: 'DIRECCION DE VIALIDAD MOP' },
    { label: 'DIRECCION DEL TRABAJO', value: 'DIRECCION DEL TRABAJO' },
    { label: 'DIRECCION GENERAL DE AGUAS', value: 'DIRECCION GENERAL DE AGUAS' },
    { label: 'DIRECCION GENERAL DE AGUAS MOP', value: 'DIRECCION GENERAL DE AGUAS MOP' },
    { label: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS', value: 'DIRECCION GENERAL DE CONCESIONES DE OBRAS PUBLICAS' },
    { label: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE', value: 'DIRECCION GENERAL DE PROMOCION DE EXPORTADORES DE CHILE - PROCHILE' },
    { label: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA', value: 'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNA' },
    { label: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE', value: 'DIRECCION REGIONAL DEL PATRIMONIO DE LA REGION DE MAULE' },
    { label: 'EMALCO', value: 'EMALCO' },
    { label: 'EMPRESA DE FERROCARRILES DEL ESTADO', value: 'EMPRESA DE FERROCARRILES DEL ESTADO' },
    { label: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE', value: 'FONDO DE SOLIDARIDAD INVERSION SOCIAL FOSIS REGION DEL MAULE' },
    { label: 'GENDARMERIA DE CHILE', value: 'GENDARMERIA DE CHILE' },
    { label: 'GENDARMERIA REGION DEL MAULE', value: 'GENDARMERIA REGION DEL MAULE' },
    { label: 'GOBIERNO REGIONAL - REGION DEL MAULE', value: 'GOBIERNO REGIONAL - REGION DEL MAULE' },
    { label: 'INDESPA', value: 'INDESPA' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO', value: 'INSTITUTO DESARROLLO AGROPECUARIO' },
    { label: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE', value: 'INSTITUTO DESARROLLO AGROPECUARIO REGION DEL MAULE' },
    { label: 'INSTITUTO FORESTAL REGION DEL MAULE', value: 'INSTITUTO FORESTAL REGION DEL MAULE' },
    { label: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE', value: 'INSTITUTO INVESTIGACIONES AGROPECUARIAS REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES', value: 'INSTITUTO NACIONAL DE DEPORTES' },
    { label: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE DEPORTES REGION DEL MAULE' },
    { label: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE', value: 'INSTITUTO NACIONAL DE LA JUVENTUD REGION DEL MAULE' },
    { label: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA', value: 'INVESTIGACION E INNOVACION TECNOLOGICA SILVOAGROPECUARIA' },
    { label: 'INVESTIGACIONES REGION DEL MAULE', value: 'INVESTIGACIONES REGION DEL MAULE' },
    { label: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS', value: 'JUNTA NACIONAL AUXILIO ESCOLAR Y BECAS' },
    { label: 'JUNTA NACIONAL DE JARDINES INFANTILES', value: 'JUNTA NACIONAL DE JARDINES INFANTILES' },
    { label: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE', value: 'JUNTA NACIONAL JARDINES INFANTILES REGION DEL MAULE' },
    { label: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA', value: 'MINISTERIO DE DESARROLLO SOCIAL Y FAMILIA' },
    { label: 'MINISTERIO DE HACIENDA', value: 'MINISTERIO DE HACIENDA' },
    { label: 'MINISTERIO DE MEDIO AMBIENTE', value: 'MINISTERIO DE MEDIO AMBIENTE' },
    { label: 'MINISTERIO DE MINERIA', value: 'MINISTERIO DE MINERIA' },
    { label: 'MINISTERIO DE RELACIONES EXTERIORES', value: 'MINISTERIO DE RELACIONES EXTERIORES' },
    { label: 'MINISTERIO DE SALUD', value: 'MINISTERIO DE SALUD' },
    { label: 'MINISTERIO DE VIVIENDA Y URBANISMO', value: 'MINISTERIO DE VIVIENDA Y URBANISMO' },
    { label: 'MINISTERIO PUBLICO', value: 'MINISTERIO PUBLICO' },
    { label: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO', value: 'MINISTERIO SECRETARIA GENERAL DE GOBIERNO' },
    { label: 'MUNICIPALIDAD DE CAUQUENES', value: 'MUNICIPALIDAD DE CAUQUENES' },
    { label: 'MUNICIPALIDAD DE CHANCO', value: 'MUNICIPALIDAD DE CHANCO' },
    { label: 'MUNICIPALIDAD DE COLBUN', value: 'MUNICIPALIDAD DE COLBUN' },
    { label: 'MUNICIPALIDAD DE CONSTITUCION', value: 'MUNICIPALIDAD DE CONSTITUCION' },
    { label: 'MUNICIPALIDAD DE CUREPTO', value: 'MUNICIPALIDAD DE CUREPTO' },
    { label: 'MUNICIPALIDAD DE CURICO', value: 'MUNICIPALIDAD DE CURICO' },
    { label: 'MUNICIPALIDAD DE EMPEDRADO', value: 'MUNICIPALIDAD DE EMPEDRADO' },
    { label: 'MUNICIPALIDAD DE HUALAÑE', value: 'MUNICIPALIDAD DE HUALAÑE' },
    { label: 'MUNICIPALIDAD DE LICANTEN', value: 'MUNICIPALIDAD DE LICANTEN' },
    { label: 'MUNICIPALIDAD DE LINARES', value: 'MUNICIPALIDAD DE LINARES' },
    { label: 'MUNICIPALIDAD DE LONGAVI', value: 'MUNICIPALIDAD DE LONGAVI' },
    { label: 'MUNICIPALIDAD DE MAULE', value: 'MUNICIPALIDAD DE MAULE' },
    { label: 'MUNICIPALIDAD DE MOLINA', value: 'MUNICIPALIDAD DE MOLINA' },
    { label: 'MUNICIPALIDAD DE PARRAL', value: 'MUNICIPALIDAD DE PARRAL' },
    { label: 'MUNICIPALIDAD DE PELARCO', value: 'MUNICIPALIDAD DE PELARCO' },
    { label: 'MUNICIPALIDAD DE PELLUHUE', value: 'MUNICIPALIDAD DE PELLUHUE' },
    { label: 'MUNICIPALIDAD DE PENCAHUE', value: 'MUNICIPALIDAD DE PENCAHUE' },
    { label: 'MUNICIPALIDAD DE RAUCO', value: 'MUNICIPALIDAD DE RAUCO' },
    { label: 'MUNICIPALIDAD DE RETIRO', value: 'MUNICIPALIDAD DE RETIRO' },
    { label: 'MUNICIPALIDAD DE RIO CLARO', value: 'MUNICIPALIDAD DE RIO CLARO' },
    { label: 'MUNICIPALIDAD DE ROMERAL', value: 'MUNICIPALIDAD DE ROMERAL' },
    { label: 'MUNICIPALIDAD DE SAGRADA FAMILIA', value: 'MUNICIPALIDAD DE SAGRADA FAMILIA' },
    { label: 'MUNICIPALIDAD DE SAN CLEMENTE', value: 'MUNICIPALIDAD DE SAN CLEMENTE' },
    { label: 'MUNICIPALIDAD DE SAN JAVIER', value: 'MUNICIPALIDAD DE SAN JAVIER' },
    { label: 'MUNICIPALIDAD DE SAN RAFAEL', value: 'MUNICIPALIDAD DE SAN RAFAEL' },
    { label: 'MUNICIPALIDAD DE TALCA', value: 'MUNICIPALIDAD DE TALCA' },
    { label: 'MUNICIPALIDAD DE TENO', value: 'MUNICIPALIDAD DE TENO' },
    { label: 'MUNICIPALIDAD DE VICHUQUEN', value: 'MUNICIPALIDAD DE VICHUQUEN' },
    { label: 'MUNICIPALIDAD DE VILLA ALEGRE', value: 'MUNICIPALIDAD DE VILLA ALEGRE' },
    { label: 'MUNICIPALIDAD DE YERBAS BUENAS', value: 'MUNICIPALIDAD DE YERBAS BUENAS' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO', value: 'OBRAS PORTUARIAS MOP REGION DEL BIO BIO' },
    { label: 'OBRAS PORTUARIAS MOP REGION DEL MAULE', value: 'OBRAS PORTUARIAS MOP REGION DEL MAULE' },
    { label: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE', value: 'OFICINA NACIONAL DE EMERGENCIA REGION DEL MAULE' },
    { label: 'POLICIA DE INVESTIGACIONES DE CHILE', value: 'POLICIA DE INVESTIGACIONES DE CHILE' },
    { label: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)', value: 'PROMOCION DE EXPORTADORES DE CHILE (PROCHILE)' },
    { label: 'SECTRA', value: 'SECTRA' },
    { label: 'SENAPRED REGION DEL MAULE', value: 'SENAPRED REGION DEL MAULE' },
    { label: 'SEREMI AGRICULTURA REGION DEL MAULE', value: 'SEREMI AGRICULTURA REGION DEL MAULE' },
    { label: 'SEREMI BIENES NACIONALES REGION DEL MAULE', value: 'SEREMI BIENES NACIONALES REGION DEL MAULE' },
    { label: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE', value: 'SEREMI DE DESARROLLO SOCIAL REGION DEL MAULE' },
    { label: 'SEREMI DE ENERGIA REGION DEL MAULE', value: 'SEREMI DE ENERGIA REGION DEL MAULE' },
    { label: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE', value: 'SEREMI DE LAS CULTURAS, LAS ARTES Y EL PATRIMONIO REGION DEL MAULE' },
    { label: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE', value: 'SEREMI DE MEDIO AMBIENTE REGION DEL MAULE' },
    { label: 'SEREMI DEL DEPORTE REGION DEL MAULE', value: 'SEREMI DEL DEPORTE REGION DEL MAULE' },
    { label: 'SEREMI ECONOMIA REGION DEL MAULE', value: 'SEREMI ECONOMIA REGION DEL MAULE' },
    { label: 'SEREMI EDUCACION REGION DEL MAULE', value: 'SEREMI EDUCACION REGION DEL MAULE' },
    { label: 'SEREMI SALUD REGION DEL MAULE', value: 'SEREMI SALUD REGION DEL MAULE' },
    { label: 'SEREMI TRABAJO REGION DEL MAULE', value: 'SEREMI TRABAJO REGION DEL MAULE' },
    { label: 'SEREMI TRANSPORTES REGION DEL MAULE', value: 'SEREMI TRANSPORTES REGION DEL MAULE' },
    { label: 'SEREMI VIVIENDA REGION DEL MAULE', value: 'SEREMI VIVIENDA REGION DEL MAULE' },
    { label: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE', value: 'SERVICIO AGRICOLA GANADERO REGION DEL MAULE' },
    { label: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE', value: 'SERVICIO DE AGUA POTABLE RURAL REGION DEL MAULE' },
    { label: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE', value: 'SERVICIO DE COOPERACION TECNICA REGION DEL MAULE' },
    { label: 'SERVICIO DE GOBIERNO INTERIOR', value: 'SERVICIO DE GOBIERNO INTERIOR' },
    { label: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION', value: 'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION' },
    { label: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION MAULE COSTA' },
    { label: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA', value: 'SERVICIO LOCAL DE EDUCACION PUBLICA MAULE COSTA' },
    { label: 'SERVICIO MEDICO LEGAL', value: 'SERVICIO MEDICO LEGAL' },
    { label: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE', value: 'SERVICIO MEJOR NIÑEZ REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA DISCAPACIDAD REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE LA MUJER Y EQUIDAD DE GENERO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE MENORES', value: 'SERVICIO NACIONAL DE MENORES' },
    { label: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE', value: 'SERVICIO NACIONAL DE REINSERCION SOCIAL JUVENIL REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE', value: 'SERVICIO NACIONAL DE TURISMO REGION DEL MAULE' },
    { label: 'SERVICIO NACIONAL DEL ADULTO MAYOR', value: 'SERVICIO NACIONAL DEL ADULTO MAYOR' },
    { label: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL', value: 'SERVICIO NACIONAL DEL PATRIMONIO CULTURAL' },
    { label: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE', value: 'SERVICIO REGIONAL DE TESORERIA REGION DEL MAULE' },
    { label: 'SERVICIO SALUD MAULE', value: 'SERVICIO SALUD MAULE' },
    { label: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE', value: 'SERVICIO VIVIENDA Y URBANIZACION REGION DEL MAULE' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES MOP' },
    { label: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE', value: 'SUBDIRECCION DE SERVICIOS SANITARIOS RURALES REGION DEL MAULE' },
    { label: 'SUBSECRETARIA DE EDUCACION', value: 'SUBSECRETARIA DE EDUCACION' },
    { label: 'SUBSECRETARIA DE JUSTICIA', value: 'SUBSECRETARIA DE JUSTICIA' },
    { label: 'SUBSECRETARIA DE PESCA', value: 'SUBSECRETARIA DE PESCA' },
    { label: 'SUBSECRETARIA DE TELECOMUNICACIONES', value: 'SUBSECRETARIA DE TELECOMUNICACIONES' },
    { label: 'SUBSECRETARIA DE TRANSPORTES', value: 'SUBSECRETARIA DE TRANSPORTES' },
    { label: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO', value: 'SUBSECRETARIA DESARROLLO REGIONAL Y ADMINISTRATIVO' },
    { label: 'SUBSECRETARIA VIVIENDA Y URBANISMO', value: 'SUBSECRETARIA VIVIENDA Y URBANISMO' },
    { label: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO', value: 'SUBSIDIO NACIONAL AL TRANSPORTE PUBLICO' },
    { label: 'SUPERINTENDENCIA DE EDUCACION', value: 'SUPERINTENDENCIA DE EDUCACION' },
    { label: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO', value: 'UNIDAD OPERATIVA DE CONTROL DE TRANSITO' },
    { label: 'VIALIDAD MOP REGION DEL MAULE', value: 'VIALIDAD MOP REGION DEL MAULE' }
  ];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute
  ) {
    this.initializeForm();
  }

  ngOnInit(): void {
    window.scrollTo({ top: 0, left: 0, behavior: 'instant' });
    
    this.route.paramMap.subscribe(params => {
      this.programaId = params.get('id');
    });

    // Actualizar comunas cuando cambia la provincia
    this.postulacionForm.get('item_provincia')?.valueChanges.subscribe(provincia => {
      this.updateComunas(provincia);
    });

    // Calcular total de beneficiarios
    this.postulacionForm.get('benef_hombres')?.valueChanges.subscribe(() => {
      this.calcularTotalBeneficiarios();
    });

    this.postulacionForm.get('benef_mujeres')?.valueChanges.subscribe(() => {
      this.calcularTotalBeneficiarios();
    });

  }

  ngAfterViewInit(): void {
    // Inicializar Google Maps después de que la vista esté lista
    this.loadGoogleMaps();
  }

  ngOnDestroy(): void {
    // Limpiar intervalos
    if (this.mapCheckInterval) {
      clearInterval(this.mapCheckInterval);
    }
  }

  private initializeForm(): void {
    this.postulacionForm = this.fb.group({
      // Información General
      cod1: [''],
      proceso_presupuestario: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      item_nombre: ['', Validators.required],
      item_descriptor: [''],
      item_etapa_postulacion: [''],
      item_sector: ['', Validators.required],
      item_subsector: ['', Validators.required],
      item_provincia: ['', Validators.required],
      item_comuna: ['', Validators.required],
      item_competencia: ['', Validators.required],
      item_distrito: [''],
      item_circunscripcion: [''],
      item_proyectorel: [''],
      item_seia: [''],
      justificacion_proyecto: ['', Validators.required],
      descripcion_proyecto: ['', Validators.required],
      item_des_indigena: ['', Validators.required],
      addressmap: [''],
      lat: [''],
      lng: [''],
      
      // Financiamiento
      presup1: [0],
      
      // Instituciones
      item_insti_formuladora: [''],
      item_insti_financiera: [''],
      institucion_tecnica_a_cargo: [''],
      
      // Resultados del Proyecto
      duracion_proyecto: [0],
      benef_hombres: [0],
      benef_mujeres: [0],
      benef_total: [0],
      item_magnitud_valor: [''],
      item_magnitud: [''],
      
      // Información de Contacto
      nombre_responsable: ['', Validators.required],
      responsable_email: ['', [Validators.required, Validators.email]],
      responsable_fono: ['', Validators.required],
      
      // Ordinario u Oficio
      num_ordinal: [''],
      ordinal_fecha: [''],
      remitente: [''],
      remite_comuna: ['']
    });
  }

  private updateComunas(provincia: string): void {
    // Actualizar comunas según la provincia seleccionada
    if (provincia && this.comunasPorProvincia[provincia]) {
      this.comunaOptions = this.comunasPorProvincia[provincia];
    } else {
      this.comunaOptions = [
        { label: 'Comuna Sin Definir', value: '' }
      ];
    }

    // Limpiar la selección de comuna cuando cambia la provincia
    this.postulacionForm.patchValue({ item_comuna: '' }, { emitEvent: false });
  }

  private calcularTotalBeneficiarios(): void {
    const hombres = this.postulacionForm.get('benef_hombres')?.value || 0;
    const mujeres = this.postulacionForm.get('benef_mujeres')?.value || 0;
    const total = Number(hombres) + Number(mujeres);
    this.postulacionForm.patchValue({ benef_total: total }, { emitEvent: false });
  }

  // Métodos para determinar si un dropdown debe tener filtro (más de 10 items)
  get shouldFilterComunas(): boolean {
    return this.comunaOptions.length > 10;
  }

  get shouldFilterMagnitud(): boolean {
    return this.magnitudOptions.length > 10;
  }

  get shouldFilterInstitucionesFormuladoras(): boolean {
    return this.institucionesFormuladorasOptions.length > 10;
  }

  get shouldFilterInstitucionesFinancieras(): boolean {
    return this.institucionesFinancierasOptions.length > 10;
  }

  get shouldFilterInstitucionesTecnicas(): boolean {
    return this.institucionesTecnicasOptions.length > 10;
  }

  onSubmit(): void {
    if (this.postulacionForm.valid) {
      console.log('Formulario válido:', this.postulacionForm.value);
      // Aquí se enviaría la postulación al backend
      // TODO: Implementar envío al backend
    } else {
      console.log('Formulario inválido');
      // Marcar todos los campos como touched para mostrar errores
      Object.keys(this.postulacionForm.controls).forEach(key => {
        this.postulacionForm.get(key)?.markAsTouched();
      });
    }
  }

  onSave(): void {
    // Guardar borrador sin validar
    console.log('Guardando borrador:', this.postulacionForm.value);
    console.log('Documentos adjuntos:', this.documentosAdjuntos);
    // TODO: Implementar guardado de borrador
  }

  // Métodos de navegación del acordeón
  siguiente(): void {
    if (this.activeIndex < this.totalSections - 1) {
      this.activeIndex++;
    }
  }

  anterior(): void {
    if (this.activeIndex > 0) {
      this.activeIndex--;
    }
  }

  irASeccion(index: number): void {
    if (index >= 0 && index < this.totalSections) {
      this.activeIndex = index;
    }
  }

  esPrimeraSeccion(): boolean {
    return this.activeIndex === 0;
  }

  esUltimaSeccion(): boolean {
    return this.activeIndex === this.totalSections - 1;
  }

  toggleSeccion(index: number): void {
    if (this.activeIndex === index) {
      // Si ya está abierta, no hacer nada o cerrarla
      // this.activeIndex = -1;
    } else {
      this.activeIndex = index;
    }
  }

  // Métodos para documentos adjuntos
  abrirDialogDocumento(): void {
    this.documentoSeleccionado = {
      id: this.generarId(),
      nombre: '',
      archivo: null,
      nombreArchivo: '',
      fechaSubida: new Date()
    };
    this.archivoSeleccionado = null;
    this.mostrarDialogDocumento = true;
  }

  cerrarDialogDocumento(): void {
    this.mostrarDialogDocumento = false;
    this.documentoSeleccionado = null;
    this.archivoSeleccionado = null;
  }

  onFileSelect(event: any): void {
    const file = event.target.files[0];
    if (file) {
      this.archivoSeleccionado = file;
      if (this.documentoSeleccionado) {
        this.documentoSeleccionado.archivo = file;
        this.documentoSeleccionado.nombreArchivo = file.name;
        // Si no tiene nombre, usar el nombre del archivo sin extensión
        if (!this.documentoSeleccionado.nombre) {
          const nombreSinExtension = file.name.replace(/\.[^/.]+$/, '');
          this.documentoSeleccionado.nombre = nombreSinExtension;
        }
      }
    }
  }

  guardarDocumento(): void {
    if (!this.documentoSeleccionado) return;

    if (!this.documentoSeleccionado.nombre || this.documentoSeleccionado.nombre.trim() === '') {
      alert('Por favor ingrese un nombre para el documento');
      return;
    }

    if (!this.documentoSeleccionado.archivo) {
      alert('Por favor seleccione un archivo');
      return;
    }

    // Validar tamaño máximo (4MB)
    if (this.documentoSeleccionado.archivo.size > 4000000) {
      alert('El archivo excede el tamaño máximo de 4MB');
      return;
    }

    // Agregar el documento a la lista
    this.documentosAdjuntos.push({ ...this.documentoSeleccionado });
    this.cerrarDialogDocumento();
  }

  eliminarDocumento(id: string): void {
    if (confirm('¿Está seguro de eliminar este documento?')) {
      this.documentosAdjuntos = this.documentosAdjuntos.filter(doc => doc.id !== id);
    }
  }

  editarDocumento(documento: DocumentoAdjunto): void {
    this.documentoSeleccionado = {
      id: documento.id,
      nombre: documento.nombre,
      archivo: documento.archivo,
      nombreArchivo: documento.nombreArchivo,
      fechaSubida: documento.fechaSubida
    };
    this.archivoSeleccionado = documento.archivo;
    this.mostrarDialogDocumento = true;
  }

  esEdicionDocumento(): boolean {
    if (!this.documentoSeleccionado) return false;
    return this.documentosAdjuntos.some(d => d.id === this.documentoSeleccionado?.id);
  }

  actualizarDocumento(): void {
    if (!this.documentoSeleccionado) return;

    if (!this.documentoSeleccionado.nombre || this.documentoSeleccionado.nombre.trim() === '') {
      alert('Por favor ingrese un nombre para el documento');
      return;
    }

    // Si se seleccionó un nuevo archivo, validarlo y actualizarlo
    if (this.archivoSeleccionado && this.archivoSeleccionado !== this.documentoSeleccionado.archivo) {
      if (this.archivoSeleccionado.size > 4000000) {
        alert('El archivo excede el tamaño máximo de 4MB');
        return;
      }
      this.documentoSeleccionado.archivo = this.archivoSeleccionado;
      this.documentoSeleccionado.nombreArchivo = this.archivoSeleccionado.name;
    }

    // Si no hay archivo, mantener el existente
    if (!this.documentoSeleccionado.archivo) {
      const documentoOriginal = this.documentosAdjuntos.find(d => d.id === this.documentoSeleccionado?.id);
      if (documentoOriginal) {
        this.documentoSeleccionado.archivo = documentoOriginal.archivo;
        this.documentoSeleccionado.nombreArchivo = documentoOriginal.nombreArchivo;
      }
    }

    // Actualizar el documento en la lista
    const index = this.documentosAdjuntos.findIndex(doc => doc.id === this.documentoSeleccionado?.id);
    if (index !== -1) {
      this.documentosAdjuntos[index] = { ...this.documentoSeleccionado };
    }

    this.cerrarDialogDocumento();
  }

  generarId(): string {
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
  }

  formatearTamano(bytes: number): string {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  }

  loadGoogleMaps(): void {
    // Verificar si Google Maps ya está cargado
    if (typeof google !== 'undefined' && google.maps) {
      setTimeout(() => this.initMap(), 100);
      return;
    }

    // Listener global para errores de carga de Google Maps
    (window as any).gm_authFailure = () => {
      console.error('Error de autenticación de Google Maps');
      this.showMapError({ type: 'ApiNotActivatedMapError' });
    };

    // Si no está cargado, esperar y reintentar
    let attempts = 0;
    const maxAttempts = 100; // 10 segundos máximo

    this.mapCheckInterval = setInterval(() => {
      attempts++;
      if (typeof google !== 'undefined' && google.maps) {
        clearInterval(this.mapCheckInterval);
        setTimeout(() => this.initMap(), 100);
      } else if (attempts >= maxAttempts) {
        clearInterval(this.mapCheckInterval);
        console.error('Google Maps API no se pudo cargar. Verifica tu API key y que las APIs estén habilitadas.');
        this.showMapError({ type: 'ApiNotActivatedMapError' });
      }
    }, 100);
  }

  initMap(): void {
    if (typeof google === 'undefined' || !google.maps) {
      console.warn('Google Maps API no está cargada');
      return;
    }

    // Coordenadas por defecto: Región del Maule (Talca)
    const defaultLat = -35.423615;
    const defaultLng = -71.649860;

    // Obtener coordenadas guardadas o usar las por defecto
    const lat = parseFloat(this.postulacionForm.get('lat')?.value) || defaultLat;
    const lng = parseFloat(this.postulacionForm.get('lng')?.value) || defaultLng;

    const mapOptions = {
      center: { lat: lat, lng: lng },
      zoom: 11,
      scrollwheel: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    const mapElement = document.getElementById('map');
    if (!mapElement) {
      console.warn('Elemento del mapa no encontrado');
      return;
    }

    try {
      this.map = new google.maps.Map(mapElement, mapOptions);
      this.geocoder = new google.maps.Geocoder();
    } catch (error: any) {
      console.error('Error al inicializar el mapa:', error);
      // Verificar si es error de API no activada
      if (error && (error.message?.includes('ApiNotActivated') || error.toString().includes('ApiNotActivated'))) {
        this.showMapError({ type: 'ApiNotActivatedMapError' });
      } else {
        this.showMapError(error);
      }
      return;
    }

    // Agregar listener para errores del mapa
    google.maps.event.addListener(this.map, 'error', (error: any) => {
      console.error('Error del mapa:', error);
      this.showMapError(error);
    });

    // Agregar marcador inicial
    this.addMarker({ lat: lat, lng: lng });

    // Listener para clics en el mapa
    this.map.addListener('click', (event: any) => {
      const clickedLocation = {
        lat: event.latLng.lat(),
        lng: event.latLng.lng()
      };
      this.addMarker(clickedLocation);
      this.updateFormFields(clickedLocation);
    });

    // Autocompletado para el campo de dirección
    setTimeout(() => {
      const addressInput = document.getElementById('addressmap-input') as HTMLInputElement;
      if (addressInput && google.maps.places) {
        this.autocomplete = new google.maps.places.Autocomplete(addressInput, {
          types: ['address'],
          componentRestrictions: { country: 'cl' },
          fields: ['formatted_address', 'geometry']
        });

        this.autocomplete.addListener('place_changed', () => {
          const place = this.autocomplete.getPlace();
          if (place.geometry) {
            const location = {
              lat: place.geometry.location.lat(),
              lng: place.geometry.location.lng()
            };
            this.map.setCenter(location);
            this.map.setZoom(15);
            this.addMarker(location);
            this.updateFormFields(location);
            if (place.formatted_address) {
              this.postulacionForm.patchValue({ addressmap: place.formatted_address });
            }
          }
        });
      }
    }, 200);
  }

  addMarker(location: { lat: number; lng: number }): void {
    // Eliminar marcador anterior si existe
    if (this.marker) {
      this.marker.setMap(null);
    }

    // Crear nuevo marcador
    this.marker = new google.maps.Marker({
      position: location,
      map: this.map,
      draggable: true,
      animation: google.maps.Animation.DROP
    });

    // Listener para cuando se arrastra el marcador
    this.marker.addListener('dragend', (event: any) => {
      const newLocation = {
        lat: event.latLng.lat(),
        lng: event.latLng.lng()
      };
      this.updateFormFields(newLocation);
      this.geocodeLocation(newLocation);
    });
  }

  updateFormFields(location: { lat: number; lng: number }): void {
    this.postulacionForm.patchValue({
      lat: location.lat.toString(),
      lng: location.lng.toString()
    });
  }

  geocodeLocation(location: { lat: number; lng: number }): void {
    if (!this.geocoder) return;

    this.geocoder.geocode({ 
      location: location,
      region: 'cl'
    }, (results: any[], status: string) => {
      if (status === 'OK' && results && results.length > 0) {
        this.postulacionForm.patchValue({
          addressmap: results[0].formatted_address
        });
      } else if (status !== 'OK') {
        console.warn('Geocodificación inversa falló:', status);
      }
    });
  }

  showMapError(error: any): void {
    let mensaje = 'Error al cargar el mapa.';
    let tipoError = '';
    
    // Detectar tipo de error
    if (error?.type === 'ApiNotActivatedMapError' || 
        error?.message?.includes('ApiNotActivated') || 
        error?.toString()?.includes('ApiNotActivated') ||
        (typeof error === 'string' && error.includes('ApiNotActivated'))) {
      tipoError = 'ApiNotActivated';
      mensaje = 'ERROR: La API de Google Maps no está activada.\n\n' +
                'Por favor, active las siguientes APIs en Google Cloud Console:\n\n' +
                '1. Maps JavaScript API\n' +
                '2. Places API\n' +
                '3. Geocoding API\n\n' +
                'Pasos:\n' +
                '1. Visite: https://console.cloud.google.com/apis/library\n' +
                '2. Busque cada API y haga clic en "Habilitar"\n' +
                '3. Espere unos minutos y recargue la página\n\n' +
                'Asegúrese de que su API key tenga permisos para estas APIs.';
    } else if (error?.message?.includes('RefererNotAllowed') || error?.toString()?.includes('RefererNotAllowed')) {
      tipoError = 'RefererNotAllowed';
      mensaje = 'ERROR: Su dominio no está autorizado para usar esta API key.\n\n' +
                'Agregue su dominio en Google Cloud Console > APIs y servicios > Credenciales.';
    } else if (error?.message?.includes('InvalidKey') || error?.toString()?.includes('InvalidKey')) {
      tipoError = 'InvalidKey';
      mensaje = 'ERROR: La API key no es válida.\n\n' +
                'Verifique que la API key sea correcta en index.html';
    }
    
    console.error('Error del mapa:', error);
    
    // Mostrar mensaje en el contenedor del mapa
    const mapElement = document.getElementById('map');
    if (mapElement) {
      mapElement.innerHTML = `
        <div style="display: flex; align-items: center; justify-content: center; height: 100%; background: #fff3cd; border: 2px solid #ffc107; border-radius: 8px; color: #856404; padding: 30px; text-align: center; flex-direction: column;">
          <div style="font-size: 4rem; margin-bottom: 1rem;">⚠️</div>
          <h3 style="margin: 0 0 1rem 0; color: #856404; font-size: 1.5rem;">Error al cargar el mapa</h3>
          <div style="max-width: 600px; line-height: 1.6; text-align: left; background: white; padding: 20px; border-radius: 8px; margin-top: 1rem;">
            ${mensaje.split('\n').map(line => `<p style="margin: 0.5rem 0;">${line}</p>`).join('')}
          </div>
          ${tipoError === 'ApiNotActivated' ? `
            <a href="https://console.cloud.google.com/apis/library" target="_blank" 
               style="margin-top: 1.5rem; padding: 12px 24px; background: #0066CC; color: white; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
              Abrir Google Cloud Console
            </a>
          ` : ''}
        </div>
      `;
    }
  }

  buscarGeoref(): void {
    const direccion = this.postulacionForm.get('addressmap')?.value;
    if (!direccion || !direccion.trim()) {
      alert('Por favor, ingrese una dirección para buscar.');
      return;
    }

    if (!this.geocoder) {
      alert('El servicio de mapas aún no está disponible. Por favor, espere un momento e intente nuevamente.');
      return;
    }

    if (!this.map) {
      alert('El mapa aún no está cargado. Por favor, espere un momento e intente nuevamente.');
      return;
    }

    this.geocoder.geocode({ 
      address: direccion,
      region: 'cl',
      componentRestrictions: { country: 'cl' }
    }, (results: any[], status: string) => {
      if (status === 'OK' && results && results.length > 0) {
        const location = {
          lat: results[0].geometry.location.lat(),
          lng: results[0].geometry.location.lng()
        };
        this.map.setCenter(location);
        this.map.setZoom(15);
        this.addMarker(location);
        this.updateFormFields(location);
        
        // Actualizar dirección con la formateada por Google
        if (results[0].formatted_address) {
          this.postulacionForm.patchValue({ addressmap: results[0].formatted_address });
        }
      } else {
        console.error('Geocodificación falló:', status);
        let mensaje = 'No se pudo encontrar la dirección.';
        if (status === 'ZERO_RESULTS') {
          mensaje = 'No se encontraron resultados para esta dirección. Por favor, intente con otra dirección.';
        } else if (status === 'OVER_QUERY_LIMIT') {
          mensaje = 'Se ha excedido el límite de consultas. Por favor, intente más tarde.';
        } else if (status === 'REQUEST_DENIED') {
          mensaje = 'La solicitud fue denegada. Verifique la configuración de la API key.';
        }
        alert(mensaje);
      }
    });
  }
}

